admin:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('ACCOUNT') }}"
      user: "{{ env_var('USER') }}"
      role: "{{ env_var('ROLE') }}"
      schema: "{{ env_var('SCHEMA') }}"
      region: "{{ env_var('REGION') }}"
      database: ADMIN_DEV
      warehouse: "{{ env_var('WAREHOUSE') }}"
      authenticator: externalbrowser
      threads: 8
      client_session_keep_alive: False
    prod:
      type: snowflake
      account: "{{ env_var('ACCOUNT') }}"
      user: "{{ env_var('USER') }}"
      role: "{{ env_var('ROLE') }}"
      schema: "{{ env_var('SCHEMA') }}"
      region: "{{ env_var('REGION') }}"
      database: ADMIN
      warehouse: "{{ env_var('WAREHOUSE') }}"
      authenticator: externalbrowser
      threads: 8
      client_session_keep_alive: False
  config:
    send_anonymous_usage_stats: False