version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'xyz' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_date_hours
      - name: address_tags
      - name: dim_dates
  - name: github_actions
    schema: github_actions
    tables:
      - name: workflows
  - name: studio
    database: bi_analytics
    schema: silver_studio
    tables:
      - name: active_databases
      - name: active_schemas
      - name: objects

